language: R
cache: packages

r_packages:
  - tidyverse
  - bookdown
  - here
  - lintr
  - spelling

script:
  - ./render_books.sh
  - ./check_style.sh
  - ./check_spelling.sh

after_success:
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

