# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - tidyverse
  - bookdown
  - here
  - lintr
  - spelling

script:
  - ./render_books.sh
  - ./check_style.sh
  - ./check_spelling.sh

after_success:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

