--- 
knit: "bookdown::render_book"
title: "TRES Tidyverse Tutorial"
author: "Raphael, Pratik and Theo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# bibliography: [refs.bib]
biblio-style: apalike
link-citations: yes
github-repo: pratikunterwegs/tres-tidy-tutorial
description: "TRES Tidyverse Tutorial"
---

# Outline {-}

This is the readable version of the TRES [tidyverse](https://www.tidyverse.org/) tutorial.

## About {-}

The TRES tidyverse tutorial is an online workshop on how to use the tidyverse, a set of packages in the R computing language designed at making data handling and plotting easier. 

This tutorial will take the form of a one hour per week video stream via Google Meet, every Friday morning at 10.00 (Groningen time) starting from the 29th of May, 2020 and lasting for a couple of weeks (depending on the number of topics we want to cover, but there should be at least 5). 

**PhD students from outside our department are welcome to attend.**

## Schedule {-}

Topic|Package|Instructor|Date*
---|---|---|---
Reading data and string manipulation|[readr](https://readr.tidyverse.org/), [stringr](https://stringr.tidyverse.org/), [glue](https://github.com/tidyverse/glue)|Pratik|29/05/20
Data and reshaping|[tibble](https://tibble.tidyverse.org/), [tidyr](https://tidyr.tidyverse.org/)|Raphael|05/06/20
Manipulating data|[dplyr](https://dplyr.tidyverse.org/)|Theo|12/06/20
Working with lists and iteration|[purrr](https://purrr.tidyverse.org/)|Pratik|19/06/20
Plotting|[ggplot2](https://ggplot2.tidyverse.org/)|Raphael|26/06/20
Regular expressions|[regex](https://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html)|Richel|03/07/20
Programming with the tidyverse|[rlang](https://rlang.r-lib.org/)|Pratik|10/07/20

## Possible extras {-}

- Reproducibility and package-making (with e.g. [usethis](https://usethis.r-lib.org/))  
- Embedding C++ code with [Rcpp](http://adv-r.had.co.nz/Rcpp.html)

## Join {-}

Join the Slack [by clicking this link (Slack account required)](https://join.slack.com/t/trestidytorial/shared_invite/zt-ejgr3tow-3zisGwPg1JDeTJD33DWb2A).

*Tentative dates.
